### PR TITLE
Create ulwgl-2016590.py

### PR DESCRIPTION
**Pull request by nmlynch94**
Adding gamefix for Dark and Darker.

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
Dark and Darker has a steam version: 

https://steamcommunity.com/app/2016590

The file name needs to follow naming guidelines:

https://github.com/Open-Wine-Components/ULWGL-database?tab=readme-ov-file#rules-for-adding-ulwgl-id-entries

Note #2:

2. If a game is on steam, the ULWGL ID will be ulwgl-steamid. If it is not, you can make up any value as long as it does not already exist.

**Comment by nmlynch94** [comment]
Thank you. Sorry about that, I did read those naming conventions, but Dark and Darker doesn't show on the store when you search it. 

I knew they weren't allowed on Steam due to an ongoing lawsuit, but it turns out they were there briefly and then removed, leaving their steam ID even though you can't search it. I've updated the PR.

**Comment by GloriousEggroll** [comment]
> Thank you. Sorry about that, I did read those naming conventions, but Dark and Darker doesn't show on the store when you search it.
> 
> I knew they weren't allowed on Steam due to an ongoing lawsuit, but it turns out they were there briefly and then removed, leaving their steam ID even though you can't actually get it from the store. I've updated the PR.

thanks! looks good now. can you also make an entry here:
https://github.com/Open-Wine-Components/ULWGL-database

**Comment by nmlynch94** [comment]
> 
> thanks! looks good now. can you also make an entry here: https://github.com/Open-Wine-Components/ULWGL-database

Done! https://github.com/Open-Wine-Components/ULWGL-database/pull/11

**Pull request merged**
